name: Build Linux

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: false
        default: 'none'
        type: choice
        options:
        - none
        - patch
        - minor
        - major
      create_release:
        description: 'Create GitHub release'
        required: false
        default: false
        type: boolean

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
        
    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y \
          cmake \
          build-essential \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libxi-dev \
          pkg-config \
          ninja-build
          
    - name: Install Qt6
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.0'
        host: 'linux'
        target: 'desktop'
        cache: true
          
    - name: Configure external dependencies
      run: |
        cd external/zlib
        ./configure
          
    - name: Get current version
      id: current_version
      run: |
        VERSION=$(grep "project.*VERSION" CMakeLists.txt | sed -n 's/.*VERSION \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"
        
    - name: Bump version
      id: version
      if: github.event.inputs.version_bump != 'none' && github.event.inputs.version_bump != ''
      run: |
        chmod +x build.sh
        ./build.sh ${{ github.event.inputs.version_bump }}
        NEW_VERSION=$(grep "project.*VERSION" CMakeLists.txt | sed -n 's/.*VERSION \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo "New version: $NEW_VERSION"
        
    - name: Use current version if no bump
      if: github.event.inputs.version_bump == 'none' || github.event.inputs.version_bump == ''
      run: |
        echo "version=${{ steps.current_version.outputs.version }}" >> $GITHUB_OUTPUT
        
    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_COMPILER=g++ \
          -DBUILD_GUI=ON \
          -DGIT_REV="${{ github.sha }}" \
          -DGIT_BRANCH="${{ github.ref_name }}" \
          -DGIT_DESC="${{ github.ref_name }}-${{ github.sha }}"
          
    - name: Build project
      run: |
        cmake --build build --config Release -j$(nproc)
        
    - name: Test binaries
      run: |
        echo "=== Checking built binaries ==="
        ls -lh build/bin/
        
        if [ -f "build/bin/shadps4-manager-gui" ]; then
          echo "✅ GUI binary built successfully"
          ldd build/bin/shadps4-manager-gui || true
        else
          echo "❌ GUI binary not found"
          exit 1
        fi
        
        if [ -f "build/bin/shadps4-pkg-extractor" ]; then
          echo "✅ PKG extractor binary built successfully"
          ldd build/bin/shadps4-pkg-extractor || true
        else
          echo "❌ PKG extractor binary not found"
          exit 1
        fi
        
        if [ -f "build/bin/shadps4-unlock-code-generator" ]; then
          echo "✅ Unlock generator binary built successfully"
        else
          echo "⚠️  Unlock generator binary not found (optional)"
        fi
        
    - name: Create distribution
      run: |
        VERSION=${{ steps.current_version.outputs.version }}
        if [ "${{ steps.version.outputs.version }}" != "" ]; then
          VERSION=${{ steps.version.outputs.version }}
        fi
        
        DIST_NAME="ShadPs4Manager-${VERSION}-linux-x64"
        mkdir -p dist/$DIST_NAME
        
        # Copy binaries
        cp build/bin/shadps4-manager-gui dist/$DIST_NAME/
        cp build/bin/shadps4-pkg-extractor dist/$DIST_NAME/
        [ -f build/bin/shadps4-unlock-code-generator ] && cp build/bin/shadps4-unlock-code-generator dist/$DIST_NAME/ || true
        
        # Make executable
        chmod +x dist/$DIST_NAME/shadps4-manager-gui
        chmod +x dist/$DIST_NAME/shadps4-pkg-extractor
        [ -f dist/$DIST_NAME/shadps4-unlock-code-generator ] && chmod +x dist/$DIST_NAME/shadps4-unlock-code-generator || true
        
        # Copy documentation
        cp README.md dist/$DIST_NAME/ 2>/dev/null || true
        cp LICENSE dist/$DIST_NAME/ 2>/dev/null || true
        
        # Create install script
        cat > dist/$DIST_NAME/install.sh << 'EOF'
        #!/bin/bash
        echo "Installing ShadPs4Manager..."
        sudo cp shadps4-manager-gui /usr/local/bin/
        sudo cp shadps4-pkg-extractor /usr/local/bin/
        if [ -f shadps4-unlock-code-generator ]; then
          sudo cp shadps4-unlock-code-generator /usr/local/bin/
        fi
        echo "Installation complete. Run 'shadps4-manager-gui' to start."
        EOF
        chmod +x dist/$DIST_NAME/install.sh
        
        # Create archive
        cd dist
        tar -czf ${DIST_NAME}.tar.gz $DIST_NAME
        cd ..
        
        echo "DIST_NAME=${DIST_NAME}" >> $GITHUB_ENV
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          dist/*.tar.gz
          build/bin/shadps4-manager-gui
          build/bin/shadps4-pkg-extractor
        retention-days: 30
        
    - name: Upload release artifacts
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v4
      with:
        name: release-linux-x64
        path: dist/*.tar.gz
        retention-days: 90

  create-release:
    if: startsWith(github.ref, 'refs/tags/v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true')
    needs: build-linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Get version
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "version=v${{ needs.build-linux.outputs.version }}" >> $GITHUB_OUTPUT
        fi
        
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: release-linux-x64
        path: release-assets
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        name: Release ${{ steps.get_version.outputs.version }}
        files: release-assets/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}